services:
  - type: web
    name: social-hub
    env: node
    buildCommand: npm install
    startCommand: NODE_OPTIONS=--openssl-legacy-provider node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: MONGODB_URI
        value: mongodb+srv://qipguruijepgwony_db_user:jepgwony@cluster0.ue21svx.mongodb.net/test?retryWrites=true&w=majority
      - key: REDIS_URL
        value: redis://default:POHokUIGlxgjAKIoZIP81oqtSQygsOHo@redis-12461.c61.us-east-1-3.ec2.cloud.redislabs.com:12461
      - key: PUBLIC_BASE_URL
        value: https://social-hub-1-brnh.onrender.com
      - key: JWT_SECRET
        value: any_random_string
      # Cloudinary Storage - ADD YOUR CLOUDINARY CREDENTIALS
      - key: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
      # WebRTC TURN/STUN - ADD THESE IN RENDER DASHBOARD  
      - key: STUN_URLS
        value: stun:stun.l.google.com:19302
      - key: TURN_URLS
      - key: TURN_USERNAME
      - key: TURN_CREDENTIAL
